article_class_name: MQsxIb xTewfe tXImLc R7GTQ keNKEd keNKEd VkAdve GU7x0c JMJvke
  q4atFc
headline_class_name: ipQwMb ekueJc RD0gLb
host: mongodb://localhost:27017/
img_class_name: tvs3Id QwxBBf
root_img: images
section: stories
url: https://news.google.com/
